### ISSUE TITLE
Fatal error since GnuPG v 2.2.17

### ISSUE THREAD

**Issue by heilingbrunner** [gpgme-sharp/gpgme-sharp#14]
Hello,

since GnuPG v2.2.17 the library (2.0.3) has a problem. The example in the folder __Examples/KeyOperations/ListKeys__ dies with an error message 

__C:\Program Files (x86)\dotnet\dotnet.exe (Prozess "23492") wurde mit Code "-1073740940" beendet.__

see below:

```
namespace ListKeys
{
	class MainClass
	{
		public static void Main ()
		{
			Context ctx = new Context();
			
			KeyStore store = ctx.KeyStore;
			
			Key[] publickeys = store.GetKeyList("", false); // <-- error
```

When i reinstall GnuPG v2.2.16 it works perfectly.

Regards.

**Comment by Daniel15** [comment]
Interesting, I wonder if something changed in that version. It might be worth asking in the `gnupg-devel` mailing list to see if the GnuPG developers know of any relevant changes in that version.

What you could try is downloading the source code in this repo, compile it yourself, and debug it in Visual Studio. See exactly which GPGME API call is causing the error to be thrown.

**Comment by heilingbrunner** [comment]
I tried this again with GnuPG v2.2.19. Same bad result. The program stops in Visual Studio without exception in the KeyStore.cs file in line 257. Only the above mentioned message on the console.

![gpgme-sharp-1](https://user-images.githubusercontent.com/1827209/70606310-76f99c80-1bfc-11ea-8d97-7c25afc2a1ef.png)

**Comment by tetrodoxin** [comment]
Today I found, that it works for me with GnuPG 2.2.19, as long as I did non use the libgpgme-11.dll of version 1.13.1.59921, that came with the GnuPG update. I used version 1.12.0.6911 of libgpgme-11.dll as before, and it seems to work.
I think I'll take a look into the differences of the library between those two versions, or try do increse library version step by step to check, since what version it is broken.

**Comment by tetrodoxin** [comment]
Well, so it seems, for me, not utilizing Gpg4Win but GnuPG Win32, it's the version 1.13.1.59921 that is broken. If I use version 1.13.1.63945 (as included in gnupg-w32-2.2.19_20191207 it works fine again.
So, as far as I am concerned, nothing wrong with gpgme-sharp :-)

**Comment by heilingbrunner** [comment]
Fine. I downloaded latest **gnupg-w32-2.2.19_20191207.exe** from [GnuPG](https://www.gnupg.org/ftp/gcrypt/binary/) and it still contains libgpgme-11.dll v1.13.1.59921. Where did you download ?

**Comment by tetrodoxin** [comment]
Strange, now that I read that, I can't find version 1.13.1.63945 of libgpgme-11.dll myself. I have to investigate this again...

**Comment by tetrodoxin** [comment]
Well, it seems, I confused some things there. I didn't have the time yet to test the libs but, I found
- libgpgme-11.dll version 1.13.1.63945 in [gpg4win-3.1.10](https://files.gpg4win.org/gpg4win-3.1.10.exe)
- libgpgme-11.dll version 1.14.0.6466 in [gpg4win-3.1.11](https://files.gpg4win.org/gpg4win-3.1.11.exe)

the gnupg-packages do indeed only have that older build of the library.

**Comment by heilingbrunner** [comment]
Today i tried gnupg v2.2.23 which includes libgpgme-11.dll version **1.14.0.280.27**.

No more exception. :-)
