### ISSUE TITLE
Question about Context life-cycle

### ISSUE THREAD

**Issue by stoyandimov** [gpgme-sharp/gpgme-sharp#15]
I am wondering what is the best way to create and dispose the context with ASP.NET Core API. The ASP.NET Core API uses DI ([Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/)). Couple of questions:

1) Is the Context thread safe?
2) Can I added it as a `scoped` service meaning reuse it within an HTTP request lifetime? Or even further can I register it as Singleton since most of the HTTP requests will interact with GPG in one way or another?

P.S. Sorry I'm using issues to ask questions. I just didn't find another way to get in touch.

**Comment by Daniel15** [comment]
I'm unsure if the library is thread safe, nor do I know how to contact the original author of the library :(

Scoped *should* be okay, just be sure to test it out for your use case. It might not be safe if you have multiple threads/tasks using the same context in parallel, but if you access it just from one place in your request it should be OK.
