### ISSUE TITLE
SetDllDirectory in Context does not work as expected 

### ISSUE THREAD

**Issue by sven-weber** [gpgme-sharp/gpgme-sharp#2]
Hi, 

we are currently evaluating if we could use your Library for our PGP Encryption but there is one Problem we faces during out tests. 
We would like to deploy a portable version of Gpg4Win [read more about portable version here](https://www.gpg4win.de/download-de.html) with our application so no installation of external Software is needed. 

As this portable version will be shipped with our app, the excecutables and libs cannot be found at the default Path and we need to adjust this path. 

Gpgme-sharp offers a Method for that: 

```cs
// First step is to create a context  
using (Context ctx = new Context())
{
    ctx.SetDllDirectory(Directory.GetCurrentDirectory() + "\\somePathInsideOurApp"); 
}
```

To our Problem: We cannot create a new Context because this throws a Exception on creation saying it is not able to find the libgpgme-11.dll because it does not exist in the default path. 

![image](https://user-images.githubusercontent.com/39764491/43122470-7035ccfc-8f21-11e8-9b39-8eae27d89d32.png)

Moreover we have a solution to the problem: 

As Context already has a static constructor I would suggest making the "SetDllDirectory" Method static. 
The Method itself only changes static values contained in libgpgme anyways. 

So instead of 

```cs
public void SetDllDirectory(string path)
{
    if (Environment.OSVersion.Platform.ToString().Contains("Win32") ||
        Environment.OSVersion.Platform.ToString().Contains("Win64")) 
    {
       ...
    }
}
```
using this
```cs
public static void SetDllDirectory(string path)
{
    if (Environment.OSVersion.Platform.ToString().Contains("Win32") ||
        Environment.OSVersion.Platform.ToString().Contains("Win64")) 
    {
       ...
    }
}
```
This would allow you to change the Path Globally before the creation of any context and we are good to go :)

```cs
Context.SetDllDirectory(Directory.GetCurrentDirectory() + "\\somePathInsideOurApp");

// First step is to create a context
(Context ctx = new Context())
{
    ...
}
```

I was not sure If I should simply make a pull request or first discuss this as a Issue. 
So I decided to first apply it as a issue because this is the better place to discuss things. 

If its OK to the maintainer I would simply add my changes as a pull request to resolve this. 

Thanks a lot in advance, 

Sven

**Comment by sven-weber** [comment]
As I noticed myself the solution mentioned above is far from perfect. 
When making the initial Method static it does not exist anymore in the normal object which is a problem I think. 

Maybe it would be better to add a additional constructor where a path can be given or make a additional static method named different.

**Comment by wget** [comment]
Hi there.

First this is not MY library per se as I have just become the maintainer. But yes, the code still needs to be refactored and ported to 2018 based C#/.NET with the ultimate goal of integrating this library to chocolatey.

Regarding your issue, personally I would prefer if you could send me a pull request with the additional constructor instead of the `static` method. I'll be happy to merge it :)

**Comment by sven-weber** [comment]
Hi, 
thanks for the quick reply. 
I opened a pull request in order to fix the issue.

**Comment by wget** [comment]
@sven-weber Thanks. I merged it. I think we can consider this issue as closed :)

Do you want me to add you some commits rights to this repository in the event you want to change things by yourself?

**Comment by sven-weber** [comment]
@wget great, thank you!

If you would like, I would appreciate that :)

**Comment by wget** [comment]
@sven-weber Done. You have just to accept the invitation :)

**Comment by sven-weber** [comment]
@wget thanks again :)
