### ISSUE TITLE
C# SetPassphraseFunction cause access violation error

### ISSUE THREAD

**Issue by timeislife** [gpgme-sharp/gpgme-sharp#4]
I am using latest ggpme-sharp with C# and VS2013, 
my GPG version is 2.2.10.
I run the example PgpEncryptDecrypt, the pinentry dialog is prompted for passphrase and the decryption works. 
then I set "pinentry-mode loopback" in gpg.conf, the MyPassphraseCallback is called, I passed the passphrase to it, 

        public static PassphraseResult MyPassphraseCallback(
               Context ctx,
               PassphraseInfo info,
               ref char[] passwd)
        {
            passwd = Console.ReadLine().ToCharArray();

            return PassphraseResult.Success;
        }

now an unhandled is throws in gpgme-sharp\context.cs which says:

"An unhandled exception of type 'System.AccessViolationException' occurred in gpgme-sharp.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

the corresponding code is at line 621:

                    int err = libgpgme.gpgme_op_decrypt(
                        CtxPtr,
                        cipher.dataPtr,
                        plain.dataPtr);

I think this maybe an issue in codes because if I decrypt using command line (gpg -d filename) and input password in the command line, the decryption also success. 

Could you please help with it? thanks.

**Comment by Daniel15** [comment]
I'm hitting this as well. If I enable native debugging, I get this error message:

> Exception thrown at 0x02D7E478 in dotnet.exe: 0xC0000005: Access violation executing location 0x02D7E478.

Unfortunately I can't find a prebuilt version of `libgpgme-11.dll` with debug symbols (Gpg4Win only includes the release build with no debug symbols), so I may need to compile it myself to be able to debug it.

**Comment by Daniel15** [comment]
Debugging this on the GnuPG mailing list: https://lists.gnupg.org/pipermail/gnupg-devel/2019-February/034190.html

I've made some changes so far, but it's still not working 100% properly: https://github.com/wget/gpgme-sharp/compare/master...Daniel15:pinentry. I'll submit a PR / land this once I get it working properly.

**Comment by Daniel15** [comment]
Fixed it... The callback was incorrectly using `stdcall` instead of `cdecl` calling convention, so it was corrupting the stack. Submitted PR #8 to fix it.

**Comment by Daniel15** [comment]
If you want to use the NuGet package, this should be fixed in 2.0.1: https://www.nuget.org/packages/gpgme-sharp/2.0.1

**Comment by MagnusGabell** [comment]
Hi, Im using 2.0.3 and the issue is the same. Raising AccessViolationException when generating the Key using the example-code from github:
https://github.com/gpgme-sharp/gpgme-sharp/blob/master/Examples/CreatePgpKey/Program.cs
GenkeyResult result = keygen.GenerateKey(Protocol.OpenPGP, aliceparam);

So it doesn't seem to have been fixed....
