### ISSUE TITLE
Ported to .NET Standard / .NET Core

### ISSUE THREAD

**Issue by Daniel15** [gpgme-sharp/gpgme-sharp#5]
Hi! Thanks to you and @danm-de for the nice library. 

I was wondering whether you're still maintaining it? I wanted to use it in a .NET Core 2.0 app, so I've ported it to .NET Standard (you can see my changes here: https://github.com/Daniel15/gpgme-sharp/pull/1) and published it to NuGet: https://www.nuget.org/packages/gpgme-sharp. I'm also planning on adding some basic unit/integration tests.

Let me know if you'd like me to submit a pull request with my changes, or add you as an admin to the NuGet package.

Thanks!

**Comment by wget** [comment]
@Daniel15 Sure you can provide send me a pull request. I would also be happy to have the admin rights on the nuget package. My nickname on nuget is `wget` as well.

**Comment by Daniel15** [comment]
Thanks, submitted as #6

**Comment by Daniel15** [comment]
@wget Actually, what do you think of moving the repo to a GitHub org rather than keeping it as just a personal repo? I just created a gpgme-sharp org and added you as an owner: https://github.com/gpgme-sharp. For example I'd like to configure Azure DevOps to build the code, but enabling it requires admin access to the repo.

**Comment by wget** [comment]
@Daniel15 Yes, I know the issue of not being an admin :) Indeed having an organization is better in this regard when doing CI stuff. I'll move the repo to the organization today. :)
If you can give me access to the CI build system, this would be nice of you.

**Comment by Daniel15** [comment]
I haven't actually configured any CI system yet... Will do that when I get
a chance.

**Comment by Daniel15** [comment]
@wget Do you think you'll move this repo to the org soon, if you're okay with that? I can set up the CI stuff once it's there. Otherwise, I could move my fork. I've got a few other PRs I'd like to submit too... Will get to those soon.

**Comment by wget** [comment]
@Daniel15 moved to the org :) You're doing a great work! :)

**Comment by Daniel15** [comment]
Nice, thanks!
